---
kind: pipeline
type: exec
name: Test & Build app
platform:
  os: windows
  arch: amd64
steps:
  - name: debug nuget
    commands:
      - dotnet add package NuGet.Protocol
  - name: Test build app
    commands:
      - dotnet build
