---
kind: pipeline
type: exec
name: Test & Build app
platform:
  os: windows
  arch: amd64
steps:
  - name: Restore project
    commands:
      - dotnet restore --verbosity d
  - name: Test build app
    commands:
      - dotnet build
